name: buenokbp
on:
  push:
    paths:
      - requirements.txt
  schedule:
    - cron: '4 */2 * * *'  # every 2 hours at minute 4

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: chk
        run: python utils.py

