name: bueno
on:
  push:
    paths:
      - requirements.txt
  schedule: [{cron: '4 */3 * * *'}]  # every 3 hours at minute 4
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: chk
        run: python utils.py


