name: bueno
on:
  push:
    paths:
      - requirements.txt 
  schedule: [{cron: '2 */5 * * *'}]  # M H d m w (Sat 1:02)
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: chk
      run: python utils.py
