name: bueno
on:
  push:
    paths:
      - requirements.txt
  schedule:
    - cron: '4 */2 * * *'  # every 2 hours at minute 4

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

#      - name: chk
#        run: python utils.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade kaggle jq
          
      - name: Set up Kaggle CLI and push notebooks
        env:
          KAGGLE_CONFIG_DIR: ${{ github.workspace }}/.kaggle
        run: |
          mkdir -p $KAGGLE_CONFIG_DIR
          cat << EOF > $KAGGLE_CONFIG_DIR/kaggle.json
          ${{ secrets.KAGGLE_JSON }}
          EOF
          chmod 600 $KAGGLE_CONFIG_DIR/kaggle.json
          
          echo "=== Kaggle CLI Version ==="
          kaggle --version
          echo ""
          
          echo "Listing kernels to verify auth..."
          kaggle kernels list --mine
          
          # Define kernels to check
          declare -A kernels
          kernels["kg"]="gadarmukha/auto-run-kernel"
          kernels["kg2"]="gadarmukha/auto-run-kernell"
          
          # Loop over kernels
          for folder in "${!kernels[@]}"; do
            KID="${kernels[$folder]}"
            echo "=== Checking status of $KID ==="
            
            # Try to get kernel status without --json flag
            if RAW=$(kaggle kernels status "$KID" 2>&1); then
              # Command succeeded - parse the status from the output
              echo "Raw status output: '$RAW'"
              
              # Extract just the status value (e.g., "complete", "running", etc.)
              STATUS=$(echo "$RAW" | awk '{print $NF}' | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
              echo "Parsed status: '$STATUS'"
              
              # Only push if kernel has completed
              if [[ "$STATUS" == "complete" ]] || 
                 [[ "$STATUS" == "canceled" ]] || 
                 [[ "$STATUS" == "error" ]]; then
                echo "Kernel has finished. Pushing new version from $folder..."
                if [[ -d "./$folder" ]]; then
                  kaggle kernels push -p "./$folder"
                else
                  echo "Error: Folder ./$folder does not exist"
                fi
              else
                echo "Skipping $KID because it is still active (status: $STATUS)."
              fi
              
            else
              # Command failed - check the error message
              echo "Status command failed. Error output: $RAW"
              
              # Check if this is a 429 error (kernel running)
              if echo "$RAW" | grep -qi "429\|too many requests\|rate limit"; then
                echo "Detected 429 error - kernel $KID is likely running. Skipping push."
              elif echo "$RAW" | grep -qi "404\|not found"; then
                echo "Kernel $KID not found. Creating new kernel..."
                if [[ -d "./$folder" ]]; then
                  kaggle kernels push -p "./$folder"
                else
                  echo "Error: Folder ./$folder does not exist"
                fi
              else
                echo "Unknown error for $KID. Testing if kernel exists by listing..."
                # Try to see if kernel exists in the list
                if kaggle kernels list --mine | grep -q "$KID"; then
                  echo "Kernel exists but status check failed. Assuming it's running and skipping push."
                else
                  echo "Kernel not found in list. Creating new kernel..."
                  if [[ -d "./$folder" ]]; then
                    kaggle kernels push -p "./$folder"
                  else
                    echo "Error: Folder ./$folder does not exist"
                  fi
                fi
              fi
            fi
            echo ""
          done
